language: node_js
node_js: lts/*

# 只监听 hexo 分支的改动
branches:
  only:
  - hexo

# 缓存依赖，节省持续集成时间
cache: npm

before_install:
- git config --global user.name "SouthFox09"
- git config --global user.email "southfoxdreamer@gmail.com"
- npm install -g hexo-cli

install:
# 安装 Hexo 及其依赖
- npm install

script:
# 生成静态页面
- hexo clean
- hexo generate

after_success:
# 部署到 GitHub Pages
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/SouthFox09/SouthFox09.github.io.git
  master