name: Blog Deploy

on:
  push:
    branches: [ haunt ]
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    strategy:
      fail-fast: false
    container:
      image: node:24-trixie
      volumes:
        - /gnu:/gnu
        - /var/guix:/var/guix

    steps:
    - uses: https://git.southfox.me/actions/checkout@v2
    - uses: https://git.southfox.me/actions/guix-shell@master
    - name: Deploy
      env:
        BLOG_DEPLOY_TOKEN: ${{ secrets.BLOG_DEPLOY_TOKEN }}
      run: |
        hy utils.hy -d ci
