#+title: FoxThinking #34: 提升免疫力？
#+author: SouthFox
#+date: 2026-07-12 20:55:26
#+tags: FoxThinking

健康是对病痛状态的否定，在病痛中才会想起健康的好，所以有没有办法能更好的抵抗疾病呢？例
如……提升免疫力？

,(read-more)

那么来看看提升免疫力的状态是怎么样的：首先免疫系统会大量生产相关免疫细胞，需要大量能量，从而减弱
消化活动，因为消化活动本身需要大量能量；其次细胞会大量分泌相关因子，导致水肿或者炎症；然后为了更有效
率的工作，大脑分泌相关因子让体温升高……没错，生病（或过敏）的状态其实就是人所谓的「免疫力」最强状态。

免疫系统由各种复杂的「组件」组成，其中一些甚至非常具有攻击性，例如中性粒细胞，甚至不惜自杀释放 DNA 和
相关蛋白质阻止敌方 [fn:1] 。面对有这等觉悟的细胞，难道还要指望它在乎「友军伤害」吗？没错，这可是事关己
身的不能高高挂起的，因为战场就在本身。而免疫系统要精准调控，不能太激烈损伤自身也不能太懒散让病原体攻
破，同时免疫系统也没有无限的能量来做事……不可避免，免疫系统也染上了「工程项目陋习」：一些 B 细胞在受
到抗原激活时会激活一次，产生勉强凑合的抗体，然后另一边的树突状细胞激活了 T 细胞，特定激活的 T 细胞碰
上活化过的 B 细胞才会让 B 细胞彻底变成浆细胞 [fn:2] 。这种先运行点东西先凑合然后搞不定再加中间层的做
法，嗯，反正我挺熟！

幸好市面上的产品并不能轻易增强免疫系统，更庆幸它不能，因为有个最臭名昭著例子就是导致大象人事件
的 TGN1412 ：作为一种人工抗体，可以与 T 细胞结合并激活它，这么看这似乎是「提升免疫力」，但后果是致命
的，志愿者在几分钟后就爆发了细胞因子风暴，造成了广泛的炎症，肿胀，器官衰竭。免疫系统作为复杂度不亚于大脑
的系统，很多发生方式和路径根本没搞明白，这个时候点击面前的那个「大又红」按钮通常可不是什么好主意。

* 阅读
*** [[https://aeon.co/essays/it-doesnt-have-to-be-us-versus-nature][Zhuangzi and the case against meritocracy | Aeon Essays]]
#+begin_quote
Deeply embedded in the ideals of justice and fairness is the idea that we ought
to get what we deserve. Deservingness is thus an intuitively compelling concept,
because we want the world to be intelligible. If the good suffer and the wicked
flourish, then the world not only becomes a painful place to live in, it also
becomes a place of moral chaos.

深植于正义与公平理想之中的，是这样一种观念：我们应当得到自己应得之物。「应得」是一个在直觉上极具说服
力的概念，因为我们希望世界是可理解的。如果好人受苦、恶人得势，那么世界不仅会成为一个痛苦的生活场所，也
会成为一个道德混乱之地。
#+end_quote

天堂与地狱、善有善报恶有恶报，这些都是深深根植于大多数人意识中的看法。

[[https://en.wikipedia.org/wiki/Just-world_fallacy][Just-world fallacy - Wikipedia]]

#+begin_quote
Confucian political philosophy begins from a premise that appears strikingly
egalitarian: the equality of opportunity. For Confucius and his successors,
human beings are more or less equal in talent at birth. Everyone possesses
the capacity for moral cultivation. Education, self-discipline and ethical
refinement remain open paths that anyone can undertake, no matter where
they’re from. This shared starting point anchors Confucian humanism: you
can make it if you try.

儒家政治哲学从一个看似惊人的平等主义前提出发：机会平等。对孔子及其后继者而言，人在天赋上或多或少
是平等的。每个人都具有道德修养的潜能。学习、自律与伦理修养是对无论其出身如何、人人开放的道路，这
一共同起点奠定了儒家人文主义：只要你努力，就能成功。
#+end_quote

#+begin_quote
The Confucian philosopher Mencius (Mengzi) articulated this idea more systematically,
which was later called ‘natural equality’: all human beings share the same basic moral
capacity. Everyone possesses the potential for goodness. Since everyone has the same
equality of opportunity, unequal outcomes and differences in social position follow
differences in effort, discipline and development.

儒家哲学家孟子更系统地阐述了后来被称之为「自然平等」的观念：人人都共享相同的基本道德能
力。每个人都有成为善人的潜能。既然人人机会平等，那么不平等的结果与社会地位差异便源于努
力、纪律与发展的差异。

‘There are some sprouts that fail to flower, just as surely as there are some flowers
that fail to bear fruit!’
「苗之不秀者有矣夫，秀而不实者有矣夫！」（P.S. 中译英之后识别是什么中还是挺有趣的）
#+end_quote

另一方面，这也带来了 meritocracy （优绩主义/精英政治），如果你能更努力，你就能更能成
功，以及，如果你不成功，那么肯定是你没有努力。这种在社会上弥漫的「永恒的功绩场」比我之前提到
的[[/2026/06/fox-thinking-31/#《在轮下》][「永恒的考场」]]更加根深蒂固。幸好，庄子站了出来，用他那讥
讽的语言回击 [fn:3] 以及点出：

#+begin_quote
Through such theatrics Zhuangzi developed a systematic critique of
Confucianism’s moral justification of inequality, and the most essential
part of that critique is his insistence that moral striving alienates us
from life. For Zhuangzi, the drive to become xian invites a person to live
for an abstraction, whether it be for reputation, moral purity or a sagely
ideal of pursuing ‘the good’. This leads one to treat their own life as raw
material for that abstract identity. One’s material body becomes an instrument
for something immaterial.

通过这些戏剧性的笔法，庄子发展出对儒家以道德不平等辩护的系统性批判；而这一批判最核心的部分
在于：他坚持认为道德追求使我们疏离于生命。对庄子而言，成为贤者的冲动诱使人为一种抽象而活——无论
是名誉、道德纯洁，还是追求“善”的圣人理想。这导致人将自己的生命当作那种抽象身份的原材。人的
物质身体变成了某种非物质事物的工具。
#+end_quote

#+begin_quote
A system that ranks people by virtue necessarily creates incentives for self-exploitation.
Once virtue becomes something that can be measured, ranked and exchanged for authority,
it turns human life into a resource to be spent. In other words, Confucian xian turns
cultivation into moral capital, and moral capital demands extraction from the self.
Indeed, one can see this kind of self-extraction in our modern neoliberal ‘hustle culture’
even more clearly, where it is trendy to ‘rise and grind’ and forego basic necessities.

一个以美德为人排序的体系必然会激励自我剥削。一旦美德成为可以衡量、排名并交换权威的东西，它就将人类生命变成了
可花费的资源。换句话说，儒家将贤能转化为道德资本，而道德资本要求从自我中榨取。事实上在我们现代新自由主义的
「奔波文化」中，这种自我剥削现象更为明显，「奋起奋斗」、放弃基本生活必需品成为潮流。
#+end_quote

不「养生」就算了，如果还追求「迫生」，那更是可悲。标榜贤圣，激励人们向这「景象」追
逐、叫人放弃自我是「不道德」的，因为这违背了[[/2026/06/fox-thinking-33/#实践命令][不要将人当成手段]]的实践命令。

我相信儒家这种道德美学「本意是好的，只是下面执行坏了」。这种「景象」初看很理想很有诱惑力，但在践行中很容易为了搞
凸显而层层加码整得极端，最后「假大空」到让旁人心生疑惑。说到这，我之前还买了本《儒林外史》，感觉是时
候来看看了。

*** [[https://nonzerosum.games/effortocracy.html][EFFORTOCRACY | NON-ZERO-SUM GAMES]]
#+begin_quote
"In the middle ages, in England, when you met a very poor person, that person
would be described as an "unfortunate"—literally someone who had not been blessed
by fortune, an unfortunate. Nowadays, particularly in the United States,
if you meet someone at the bottom of society, they may unkindly be described as
a "loser"."—Alain de Botton

“在中世纪的英格兰，当你遇到一个非常贫穷的人时，那个人会被称为'不幸者'——就是单纯指没有被幸运眷顾的
不幸之人。如今，尤其是在美国，如果你遇到社会底层的人，他们可能会被不友好地称为「失败者」。——阿兰·德波顿
#+end_quote

non-zero-sum games 之前也写了篇关于优绩主义的文章。

奖赏在道德里「公平公正」也是绕不开的讨论点，对于努力与回报，大体分为两种导向 [fn:4] ：

- 功利主义：也即结果导向，奖励产出更多成果的人也有助于激励他产出更多结果，这在当前世界可能是最大众
  最「默认」的观点？不过功利主义的问题是：以什么维度衡量结果？例如以儒家惯例的讨论场中，如果统治者
  不以美德作为结果而是以自身愉悦作为结果，那么只会「产出」更多谄媚小人而压制君子。
- 回报主义：也即努力导向，既是文章中提到的 EFFORTOCRACY ，如果你越努力就越应该得到奖赏。这种主义
  指导下能够更能指导那些从爬出谷底的人——从谷底爬到水平面和从水平面爬到山顶的高度是一样的。但这种主
  义的问题就是，会让较为有能力的人另谋高就。例如在讨论场  [fn:5] 上反复拿出来说的：欧洲因为更
  加「敌视」有能力的人和重视公平，对高收入者征以重税，有能力的人都跑到美国去了，所以也导致现在欧洲的
  经济一直低迷。

*** [[https://guix.gnu.org/en/blog/2026/one-year-with-codeberg/][One year with Codeberg — 2026 — Blog — GNU Guix]]
Guix 项目迁移一年后的感想，我很惊讶迁移到 Codeberg 这种代码 forge 平台，用上新生代黑客熟悉
的 PR 流程竟然没带来很明显的贡献人数增多现象。

*** 《战斗细胞：人体免疫系统奇妙之旅》
免疫系统和病原体就像是一场持续几十亿到现在还在继续的乒乓球比赛，双方你来我往互有胜负。理解起来确实蛮
有意思，毕竟这就是发生在每个人身上的事啊。

**** 穷举到世界尽头
面对几十分钟就能分裂一代的细菌病毒们，人体的免疫系统该怎么跟上对面的步伐？在不断变异的病毒细菌看
来，人的免疫系统就跟慢动作树懒一样。

免疫系统给出的答案是……穷举！大家都是从几十亿年前海洋出来的，蛋白质构件都是那些，所以我只要一件一件
拼出来不就好了，适应性免疫细胞就会这样不断随机混合基因片段，形成未来可能会遇到病原体的受体……不过做
法一个最大的漏洞就是如果出现了刚好匹配自身人体细胞的免疫细胞该怎么办？在免疫细胞受训的胸腺里，会有
专门的「教官」拿着特权生成人体种心脏、胰腺、肝脏等器官的蛋白质 [fn:6] ，如果受训的细胞表现出识别
的迹象，「教官」就会命令其自杀防止让它永远毕业不了。当然，理想情况下是这样，生命从不缺意外。一旦
能攻击自身人体的细胞从胸腺逃逸出来，那就可能就会发展成狼疮、风湿等自身免疫病了。

**** 宿敌就是宿敌啊
书中里还专门花了一章来讲寄生虫 [fn:7] 。现在寄生虫状况改善，让免疫系统对付寄生虫的肥大细胞、嗜酸（碱）性粒细
胞「闲」下来，（加上寄生虫和免疫系统互相对抗中弄出了欺骗，掩盖，绕过的方法，也压制了免疫系统强度），从而
让现在过敏状况更多见了。甚至免疫系统天生就更喜欢「熟人」，是为了常见的威胁而存在的。面对全球化的世界，可能指不
定就能从飞机上隔壁座位来自世界对面的人上飞来一些完全不熟悉的病原体，这也是免疫系统在新世纪要面对的新问题吧。

** 一呼百应
又是新专栏，是关于游戏的。至于为什么取「一呼百应」呢？因为在所有的艺术形式中，电子游戏是最能体
现「call and response」的。其它艺术中需要「主动」投入很多精力去接收作者想要的信息，而且作者要预
先埋下「呼应」，期盼着观者也产生相同的呼应，在后面再抛出「回答」才是完成了「call and response」。
而在电子游戏中，用方向键就能很直观操作屏幕上的「游戏精灵」 [fn:8] 。通过编排脚本，在达到某
个阶段时，光影、音乐、对话、文字都能齐齐调动起来，这就是我给专栏起这名的原因了。

*** 女神异闻录5: 皇家版
过了几年回来玩，发现 16 年的游戏里头讲的自决、监狱之类的隐喻在现在 26 年看来真是一语成谶了，无论是疫
情还是什么下行周期吧，明显感觉人们都很累，都不想自己做决定。

倒是对游戏代入感有帮助啦，不过感觉滋味有点复杂。

*** 小小书店
游戏开头就抛出了很有意思的「幻景」，抛开过去经营流动书店。不过这个「幻景」在三小时后就「幻灭」了，只是变成了好
像有那么回事的经营游戏。不是说这样不好，毕竟想了下要满足这个「幻景」要做的努力太大了。不过游戏为了经营要素
做得让步确实有点让我哭笑不得？比如装饰根本不是为了装饰而是什么数值高就放哪个，为了达成目标开始 SL ……不过至少确
实游戏氛围还是挺放松的，而且游戏本地化也用心的为不同语言准备了不同的书籍，搞得我都有点兴趣开个新档看看其它语
言中会是什么书了。

*** 魔兽世界
等等党的胜利，现在我就是随便逛逛上去看点最新剧情和旧时任务的剧情，不过魔兽设计师确实比我对「现代社会」更有洞
察。例如现在版本正在追求「让单人玩家通过单人玩法也能拿到毕业装」的设计理念，这对以打团和装备驱动的网游在之前
可真不敢想，也是现在社会愈加原子化的一个例子。

** Dynamically typed
*** [[https://blog.racket-lang.org/2026/06/rhombus-v1.0.html][Rhombus v1.0]]
Rhombus 是基于 Racket 的中缀记法语言，这下倒是有点倒反天罡了。不过看起来象牙塔里的魔法师们确实想要出
手为中缀记法语言带来点新东西了。嗯，加入到我的观察名单里吧……

** Present day, Present time
哎呀，又成死线战士了。倒是在准备一件之前一直落下的事情，所以拖慢了这期周刊的进度。不过就算搞不定，下期作
为第 36 期也是到了总结期了。

** 脚注
[fn:1]  [德]菲利普·德玛特. 战斗细胞：人体免疫系统奇妙之旅. 海南出版社. 2023, 第 66 页.

[fn:2]  [德]菲利普·德玛特. 战斗细胞：人体免疫系统奇妙之旅. 海南出版社. 2023, 第 140 页.

[fn:3] 详情可参阅：
- [[https://ctext.org/zhuangzi/cutting-open-satchels/zh][《胠篋》 - 庄子 | 中国哲学书电子化计划]]
- [[https://ctext.org/zhuangzi/robber-zhi/zhs][《盗跖》 - 庄子 | 中国哲学书电子化计划]]

[fn:4] [美]雅克·蒂落. 伦理学与生活（第11版）. 四川人民出版社. 2020, 第 127 页.

[fn:5] 当我说「讨论场」的时候，其实就是「网上说」、「大家说」、「其他人说」：我懒得查证但不过先拿出来就这么
说了做法的一种更文绉绉的说法。

[fn:6]  [德]菲利普·德玛特. 战斗细胞：人体免疫系统奇妙之旅. 海南出版社. 2023, 第 117 页.

[fn:7] [德]菲利普·德玛特. 战斗细胞：人体免疫系统奇妙之旅. 海南出版社. 2023, 第 257 页.

[fn:8] [[https://zh.wikipedia.org/zh-cn/%E7%B2%BE%E7%81%B5%E5%9B%BE][精灵图 - 维基百科，自由的百科全书]] ，简单来说就是在动的物品或人物。
