#+title: FoxThinking #17: 想想春天的速度
#+author: SouthFox
#+date: 2026-02-09 21:15:23
#+tags: FoxThinking

过了立春，阴冷的寒气正在消散，开始能感受到天空中的若有若无的春气，可我怎么还在搞服务器。

,(read-more)

之前在[[/2026/01/fox-thinking-13/][节气差异]]周刊里摆弄节气时就在想着看看季节的速度了。这个世界是连续的（如果你是在
普朗克尺度下过活的人或智慧生命，请联系我），意味着事物总有个发展的过程。季节中每天的进
展应该能「测量」得到，是气温吗？或许诗意一点可以是报春植物的情况，测测一天过去，植物花朵开放
的「阵线」往前推进了多少公里就是「春天的速度」了。

我很想获取点数据算算看春天的大概速度然后在春天实际到来那天好好加强一下感官品味下周
边，就当是在「迎客」。可惜上周所有能做事的时间都丢给了服务重装上，没有什么时间推进其它感兴趣的
事上，希望能在春天实际来到我这里前把自托管服务部署好。

** Present day, Present time
因为上周都是在搞自托管的事（几口气部署了十二个服务），所以没什么精力读点东西了，不过折腾中也是鼓捣了
挺多东西的，希望在结束相关部署后能够整理出一些博文出来，这里先简单提一下：

*** All in podman
将新装的服务都用普通账号 Rootless 容器部署了，折腾起来踩了很多坑，基本上也都是因为 Rootless 导致
的。在排错网络、文件权限之类的问题开始怀疑为了这没体验过的安全性弄得这么麻烦值得吗？不过至少最后也算是
弄出来了吧。

没有守护进程的 podman 明显好处就是 http_proxy 这种环境变量说设就是设了，终于不用怀疑到底是代理的问题
还是容器编排层面还是容器里面的问题了……感觉每个试图尝试用环境变量指定代理的 docker 用户都踩过这个坑。然后是
得自己去手动持久化容器，可能对其他人要 export 成 systemd service ，对我来说刚好能用 shepherd 来管理，
所以也不是一个麻烦的点。

*** 很多地鼠
从头开始的机会意味着能选些其它服务，我把之前的 matrix 聊天服务从 synapse 换成了 continuwuity ，
wallabag 换成了 readeck ：一个用 Go + Sqlite 的稍后读
应用。很轻巧却也有很多小毛刺，比如没有用 GET 触发获取文章的方式导致依赖插件或者自己用 API 糊啦、没有重新拉取
文章啦、文章竟然不排重啦等。不过鉴于 readeck 技术栈比起 wallabag 的 php 确实更合适个人使用
就先自适应了，如果实在受不了那就临阵学点 Go 然后自己改吧。

发现自己用得很多程序和工具都是用 Go 写的，难道我真该正经学下 Go 了？

*** 大吃特吃树莓派
也是将一些明显只有自己在用的 rss 阅读器还有稍后读应用都拆开来部署到树莓派上了，甚至最后还部署了个 Vaultwarden 密
码管理服务和 Searxng 聚合搜索服务。现在树莓派爆炸下线的话会让我感到很麻烦了，或许这也是我在好好利用
树莓派的表现吧。

*** 大阵炼成
如果只是简单的部署使用一些服务确实不费什么精力时间，不过这周我在把部署这套流程融进我的 Guix 配置里，誓要做到一套
配置 reconfigure 后就能直接阵法展开，将相关服务以及参数还有最后的备份流程给准备好，这里耗掉的精力就多了。今天
还弄了一下 zfs ，打算用上面的原子化快照来方便后续的备份流程（否则 forgejo 下面的一大堆仓库用 dump 来备份也太
折磨人了）。

不过这些东西就是很水磨工夫要自己慢慢推进，等我干好以后就一定要……可惜运维这事想做的话总能挑出点活来做，希望能尽快爬出
这个兔子洞吧。
