#+title: FoxThinking #19: 不要恐惧
#+author: SouthFox
#+date: 2026-02-23 21:22:18
#+tags: FoxThinking

别人恐惧我就摸鱼。

,(read-more)

就算是只靠 RSS 摄取新闻的人也能发现现在变化的速度太快了，聊天、模型、蒸馏、微调、MCP、Agent、
OpenClaw ……感觉个把月就有新的概念提出来。不由得让人产生一种比错失恐惧（Fear of missing out，简
称：FOMO）更深入的恐惧，恐惧变得过时（fear of becoming obsolete, 简称 FOBO）。

要说我没产生过焦虑那当然是在说谎，只是我花了点时间想了想得出了下面的推论：

如果以后人工智能的发展真能达到「他们」所宣扬的那样简便好用无需任何背景知识，那么直接用就是了，可能
就像是什么「无条件基本收入」吧；或者依然还需掌握相关知识背景的人来编排、管理相关资源，那么等用到的
再学也不迟，临时抱佛脚可不是稀奇的事。我在现在看到的尽是沙堡，没有什么能长久存在的东西……

况且关于「过时」，想想我现在用着 Emacs 配点 Lisp 语言写出这篇博文我就觉得，「过时」似乎并没有什么
太在意的，二三十年前人们写着 if-else 现在仍然写着 if-else ，我相信二三十年后依然需要 if-else 。
我想还是把精力放在更值得关注的事吧，例如「更值得过的生活是什么样的生活？」，这个老问题已经存在了许久，
古代哲人近代哲人都作出了很不错回答，但并没有个百分百适合我的回答，相信就算之后出现能作出最
佳回答的「AI 哲人王」也不行。

** 阅读
*** [[https://phys.org/news/2026-02-exploring-children-struggle-math.html][Exploring why some children struggle to learn math]]
为什么有些孩子在数学学习上有困难？这些孩子并非不理解相关逻辑，而是监测和调整行为相关区域的活动较弱，或者
换个方式说，就是倔，无法改变自己对错误的认知。

不只是儿童可能成人也有这种倾向，在工作中遇到相同报错出现了几次日志就往上翻几下就能找到原因但还是
一直死磕的人，可能这就一种相同的特质，推测这种特质对于在一条道路走下去的场景是会有所帮助吧。
嗯，大脑，真神奇啊。

*** [[https://www.iankduncan.com/engineering/2026-02-05-github-actions-killing-your-team/][GitHub Actions Is Slowly Killing Your Engineering Team - Ian Duncan]]
又一篇对 Github Actions 的吐槽文，可情况确实如此。Github 上 Action 日志查看卡死我的浏览器已经是频频出
现的事了，甚至我还不是老机器，而是去年买的 32G 内存搭载 Intel Core Ultra 9 285H (16) @ 5.4GHz CPU 的
设备，这对于一个大公司来说是会出现的问题吗（不过想到现在微软能让记事本都出远程执行漏洞，我就释怀了 [fn:1] ）？

而且在 CICD 明显要往更通用配置和流程管理的方向发展时，继续守着折磨人的 Yaml 和有点让人惊讶的 npm 生态还是
不太行，现在的集成工程师值得用一个更加适用的编程语言来管理复杂度和整个流程。

*** [[https://gaiwan.co/blog/why-clojure/][Why Clojure?]]
为什么用 Clojure ？因为 Clojure 对于使用它的人也提出了更高要求，我觉得用编程解决问题应该是件满足好奇并且
快乐的事，所以我觉得用 Clojure 就挺好的。

*** [[https://mp.weixin.qq.com/s/1AdcYfVqo4kIQ09RyiPXeQ][那艺娜：滤镜之下 - 微信公众号]]
梗后真实的人……

** Present day, Present time
春节假期结束了，勉强坚持结构性没被打碎，比去年好了点。不过自己想做的事倒是没做出多少还是有点遗憾，不过往好了想
至少还是尽可能把人际关系打理了下。谁能真正做到真正独行呢？有个情感支持网还是很有必要，不过对我这种只想躺在
被窝里待着不动的狐来说短时间高强度社交还是有点太超过了……

** 脚注
[fn:1] [[https://www.solidot.org/story?sid=83538][奇客Solidot | Windows 记事本爆出一个远程代码执行漏洞]]
