#+title: FoxThinking #33: 背景音
#+author: SouthFox
#+date: 2026-06-28 18:51:57
#+tags: FoxThinking

不要变成那喧嚣的背景。

,(read-more)

终于把靠窗椅子上堆积的衣服收拾好，看着天空比较阴沉但还没到无法阅读的程度，索性
就拿了本《悉达多》开始读。在读到悉达多在河中听到「成百种声音、上千种各色各样
的声音」的「悟道」情节时，惊觉天空中的乌云已经飘过，天空明亮了起来。望着窗
外道路上的车流，听着车流声陷入恍惚……

回过神后，心里想起的是：我好像一直在听着车轮在公路上的声音。今年租房合约到期
时，我有机会找处更好的地方还是选择了续期，除了最主要的不想麻烦外，或许还有个
隐藏的原因是因为这方靠近公路，若隐若现的车轮滚滚声让我感到熟悉。之前的房子也
是毗邻道路的高层房，在夜深时最明显的声音就是车辆行驶的声音。将近十年，这种声音
已经成为了我的背景音。

或许除了车流声，我还怀念火车声：更小的时候住在火车轨道旁，火车驶过巨大的声音却并
没有吵醒我（或者吵醒了我也没这一两分钟的记忆），不由得感叹环境的力量。

熟悉的声音让人心安，倒是有例可循。比起热带森林下的录音，来自更熟悉的当地
森林录音让研究参与者报告了更积极的情绪：

[[https://phys.org/news/2026-04-soundscapes-nearby-forests-uplifting-faraway.html][Soundscapes from nearby forests are more uplifting than those from faraway places, research suggests]]

说起自然的声音，我也能列举一些：同样声音巨大到令人震撼的花狭口蛙、听到就知道熬穿夜
的珠颈斑鸠和白头鹎、迟迟嚎不到最高处让人心烦的噪鹃……

** 阅读
*** [[https://www.quantamagazine.org/how-many-elementary-particles-are-there-really-20260615/][How Many Elementary Particles Are There, Really? | Quanta Magazine]]
「物质由什么组成」这种基础的问题，答案都很复杂和混乱。在追问「为什么这个宇宙
这么复杂？」的同时，或许也更该想到有些时候就是不能奢望事事都是[[/2026/04/fox-thinking-24/][简单的事]]啊。

*** [[https://knowablemagazine.org/content/article/technology/2026/what-shapes-ai-moral-decisions][How will AI make moral decisions for you and me? ]]
确实该思考人们越来越开始将道德决策转交给大模型后产生的现象和影响了，不知
道会不会有学者在相关领域提出堪比电车难题那般「臭名昭著」的道德难题。

*** [[https://phys.org/news/2026-06-india-hotter-summers.html][India learns to live with hotter summers]]
印度热完欧洲热，加上我 RSS 源里继续刷屏的厄尔尼诺相关条目，就感觉非常非常风
雨欲来，希望不要变成什么更糟糕更恶劣爆炸事件里的油罐吧……

*** 《悉达多》
整理书堆时发现自己其实买了两本《悉达多》，最担心的事还是发生了，没记住已经
买的书然后买重了。不过幸运的是两本版本不同，这本之前买的徐进夫译本带上了详
尽的注释，重读时对着注释读颇有收获。

*** 《哲学简史》
将西哲按照时代划分然后在时代走马观花般认识下对应的哲学家、著作、思想，虽然很
入门，但可能也比较适合用来作为某个更大学习计划的「索引」。不过我光看点古希腊
的哲学就感觉挺多了……不过慢慢看吧，反正来都来了也都不容易，可能慢慢看着看着就
觉得习惯就好，兴许赶在人都死了前岁数大了时都能看完呢？

*** 《老子今注今译》
还是觉得至少把《道德经》通行本背下来比较好，这样去看帛书版、郭店版、河上
公版比较异同时也有个底本比对（ diff 至少也得提供原文件啊）。选择通行本也
能跟众多研究能对上号，之后在考虑往小众的地方钻，这种先大众再小众的做法感
觉也是我一直在应用的。

不过在背的同时想着为了加深印象选择边抄边背，不过正文却是繁体字，想着无所谓顺带
学点繁体字吧。期间感想是所谓国人自带简繁转换插件，主要还是可从上下文和依稀几个
偏旁推测出来，如果是单字单拿出来看，没正经学过还真不知道是什么。

*** 《伦理学与生活》
同样走马观花式地讲伦理道德的书，也同样可以作为以后精细的学习的「索引」。
里面的几个点我也确实挺感兴趣：

**** 绝对命令
绝对命令断言，如果认为某一行为规范不能为一切人执行，那么该行为就是不道德
的。[fn:1]

如一个懒汉想：「为何要辛苦劳作何不偷窃」然后问及背后的准则「我将永不劳作，而
从别人那偷取所需之物」。如果将其推广至全人「谁都不该劳作，人人都应互相偷取自
己所需之物」，那这样就无人劳作，无东西可偷。因此偷窃不能适用一切人，所以是不
道德的。

**** 实践命令
在道德上来说，任何人都不应该仅仅被视为或作为别人目的其手段，每个人本身就
是独特的目的。 [fn:2]

关于这一点，体现不道德绝佳例子就是互联网服务，将人称作「用户」，视人做仪表盘
上的一列列指标，然后不停实验如何操作这指标。这个文章视频会激起人们的争吵、带来
焦虑、散布恐慌？无所谓，它能带来留存，指标够好，何必在乎背后是什么人呢？

不过要是能将人的作为目的，或许康德会同意吧。例如一个罕见病患者，实验性疗法能为
相关患者带去更多经验，同时也可以治疗患者本身。那么这名患者成为了手段也成为了目
的。

**** 决定论
反对（机械）决定论观点的人很多，我也从「决定」这个角度上添一笔：就算事出有因，我们
可能也无从知道到底是什么因。生物除了遗传带来的潜在特征，环境同样也是重要的原因。遗传
所带来的都尚不清楚，何况环境呢？某人行事大大咧咧或许是因为他小时候喝的水里水垢
比较多、附近的鸟儿叫声比较响导致的；或者一位深陷网贷网赌的大学生，却因为视频网站看
到了戒社的视频而痛哭流涕，然后痛改前非浪子回头。这里的因还能将这个绑
在 /dev/(u)random 这种随机数生成器上，更加让人难判断因的出处了。

而对于自由意志来说，人的大脑就是个接受万万亿个参数层层累加的神经网络黑
箱，而这正是 [fn:3] ：

#+begin_quote
但是——用霍斯普特的话来说——在某种程度上（人与人的差别很大）和相当
长的时段里，对于想望或不想望、选择或不选择、行动或不行动，我们都是
自由的。
#+end_quote

** Dynamically typed
*** Project Gutenberg
古腾堡项目是我一个多月前就想说的网站，不过我忘了。

[[https://news.ycombinator.com/item?id=48150431][Project Gutenberg – keeps getting better | Hacker News]]

这次倒是想起来了，因为最近出现了古腾堡假冒的钓鱼网站，不免有点气愤怎么还将这种
网站作为目标：

[[https://mastodon.social/@gutenberg_org/116818071367339030][Project Gutenberg: "Be aware that a malicious website is using gutten…" - Mastodon]]

*** [[https://www.shuge.org/shisan_sui/][十三周年，愚公移山 – 书格]]
当然也有古腾堡项目类似的书格项目。对于此类项目，我只能涨红了脸，额上的青筋条条
绽出，憋出什么「互联网精神」，什么「每个人的自由发展」之类什么说烂的话。

** Present day, Present time
这一周都在看吃蛋挞的折棒的新三国吐槽视频系列，惊恐的发现我在凭此了解
三国！例如刘关张是怎么起家、曹操的出身是怎么样、手离戟把越近就离义
父越远的吕布董卓是咋回事……

说来惭愧，对于历史我已经很模模糊糊，对于年表就有个模模糊糊的印
象：上古夏商周、礼崩乐坏但百家争鸣春秋战国、秦汉、然后一锅乱到隋、最后唐宋元明清。
毕竟对历史的认识是为了应试而死记硬背的提纲，不出几年就忘了，现在已经没有成体系
的认识。不过随着现在越发有兴趣同时也能任由自己兴趣回看历史，这种情况应该能有
所改观吧。

** 脚注
[fn:1] [美]雅克·蒂落. 伦理学与生活（第11版）. 四川人民出版社. 2020, 第 57 页.

[fn:2] 同上

[fn:3] [美]雅克·蒂落. 伦理学与生活（第11版）. 四川人民出版社. 2020, 第 115 页.
