#+title: pali open
#+author: SouthFox
#+date: 2026-06-24 00:51:55
#+lang: tok
#+tags: 日常

mi pilin ike tan ni: pali mi li pini kama.

,(read-more)

sinpin mi li len e pilin ni. tenpo suno pi pali ala la,
mi wile lape mute. tenpo suno pi pali la, tenpo lape mi li nasa.
ni li pana e sona ni: insa lawa mi la, pilin ike en pilin wile
li awen lon.

tenpo suno sike mute li pana e pona mute tawa insa mi. mi kama sona
e kulupu, ni li pana e sona wawa: mi wan li ken pilin pona.

mi pana e pona mute tawa kulupu. pali ona li suli ala, ona li
pana e tenpo mute tawa mi. mi ken kama e ijo sin, mi
ken kama suli lon nasin mi. taso lon tenpo ni la, tenpo pi weka kama.
lon la, mi wile tawa ma ante lon tenpo kama, mi wile open
e open sin. taso ijo ni li kama lon tenpo ni. ni li kama weka tan
tenpo wile mi. ni li nasa lili tawa mi.

lon tenpo suno ni la, mi alasa e nasin tawa ni: mi kama pona.
mi sitelen kepeken luka e lipu suli "Tao Te Ching" tawa ni:
lawa mi li ken sona jo e ona. kin, mi lukin e lipu ante, mi
open sin e pali meso pi tenpo pini, mi pali e ni: ona li kama
pona mute. nasin ni li pana mute e pona tawa mi.

taso tenpo li tawa la, mi wile pali e ijo tawa open sin.
ijo mute li kama lon tenpo sin. tenpo ni la, mi wile pali open!
