language: node_js

cache:
  npm: true

node_js:
  - "12"

before_script:
 - rm -rf node_modules
 - rm -rf .git
 - git clone https://github.com/hexojs/hexo-theme-unit-test temp
 - mkdir temp/themes
 - mkdir temp/themes/landscape
 - rsync -av ./ ./temp/themes/landscape --exclude ./temp/
 - cd temp
 - npm install
 - cd themes/landscape
 - npm install

script:
  - npm test
  - cd ../..
  - hexo g && hexo g
