#+title: FoxThinking #11: 季度总结
#+author: SouthFox
#+date: 2025-12-28 21:22:30
#+tags: FoxThinking:Lisp

第十二期！这就说明周刊的试运行期就已经结束了，是时候做个回顾了。

,(read-more)

** 回顾
没想到十月份一时兴起「办周刊」的念头没有成为「三分钟热度」而是变成现在「三个月热度」。可我还是个「死线」人，每次
直到星期天晚上八九点的时候才匆匆忙忙来写点，这个周刊可能有点糊弄但至少还是憋了点东西出来的。三个月过去了对这个
周刊评价为「马马虎虎」吧，虽然评价就这样但依然还是决定办下去。

那么之后就每逢十二期以一个季度为周期进行回顾，审视下这这三个月的内容（一个月感觉东西有点少所以拖到三个月吧）。

- [[/2025/10/fox-thinking-1/][#1: 互联网殖民时代]]：这是对这个大模型时代下的牢骚，因为真得很烦人。我在一个互联网独居一隅怎么突然间就围得水泄不通然后
  哐哐哐一大堆噪声……之后部署了在周刊 #3 里提到的 [[https://maurycyz.com/misc/the_cost_of_trash/][You should feed the bots: (Maurycy's blog)]] 这个项目。效果
  很好，针对这种不要脸面的爬虫用最小的代价打发掉也算是优选了。一个月后看 nginx 访问日记甚至还气笑了，因为里面的相关
  路径的爬虫 UA 里赫然是一些国内「有头有脸」的XX云之类的厂商。问题来了，这些蜜罐路径仅由在 robots.txt 禁止
  爬取的路径上跳转过来的，你们这些爬虫是从哪里得知这些路径的呢？

-  [[/2025/10/fox-thinking-2/][#2: 震惊！你的脑袋正在控制你？！]]：如何「骗过」大脑？庆幸大脑能复杂到足以思考大脑本身产生这种元思考吧，这是一个值得
  深挖的话题，之后打算看点心里学相关的书，为了——「人啊，认识你自己的大脑！」。

- [[/2025/11/fox-thinking-3/][#3: 这是括号的世界，我很幸运活在其中]] 和 [[/2025/11/fox-thinking-4/][#4: 未读未读未读已读]] 里就是（本博客）老生长谈的 Emacs 和 Lisp 了，看起来
  这个话题在下一年还会继续下去……
  - [[www.afterbabel.com/p/on-the-death-of-daydreaming][On The Death of Daydreaming - by Christine Rosen]] #3 里提到的拿「空闲时间」发呆和走神的做法，践行后好像
    确实会比刷只能手机更有「想法」一点，也对这个周刊起到了点点帮助吧。有时候就是得拥抱无聊，无聊没什么不好的。

- [[/2025/11/fox-thinking-5/][#5: 何以为电子游戏]]：在工作后越发感到自己的热情在渐渐流失下感慨有时候有「欲望」也是一件困难的事。

- [[/2025/11/fox-thinking-6/][#6: 珍视是最大的浪费]]：在树莓派布置好后就没有动过它了，虽然对于树莓派这种设备是常事不过感觉还是有点浪费，可能跟
  树莓派这个需求就是硬凑出来的有关吧，之后还是得多「吃」点派多用上用上。

- [[/2025/11/fox-thinking-7/][#7: 无限猴子与刍狗]]：因为生病糊弄的一篇，有点为说而说去摆弄旧词的意思……

- [[/2025/12/fox-thinking-8/][#8: 守住八分地]]：二八定律是一个通用定律，知晓它在不同系统中看到这种通用范式出现后就
  能让人「安心」，这种优雅之处是人类这么着迷通用定律的原因啊（大一统定律：叫我？）。这里我通过二八定律发散了下当今互联网：
  互联网在极化吗？应该是吧，就算是这是那百分之二十里巨无霸的趋势，也不要忘了二八定律是一个「自组织临界性」系统，无足轻重
  百分之八十里的个体也能激起一些涟漪在这个系统不停震荡产生些什么……

- [[/2025/12/fox-thinking-9/][#9: 边缘行者]]：现在想来，其实更常见的「边缘行者」就是一众「多语者」，为了讨生活或只是
  兴趣使然凭借另一门语言驶向另一个文化圈……

- [[/2025/12/fox-thinking-10/][#10: 限制会带来……]]：限制有时候也带来繁荣，就像这个周刊一样，我随意定下的「每期周刊都得
  有个主题」这个限制给我带来了数个抓耳挠腮的星期天晚上，但也带来了点产出不至于散成一团。有个主题确实更引人入胜一点，如果
  只是简单列出看了啥然后简单摘抄的话，我觉得连我自己事后看起来都会让眼睛干到「噎」住吧。

在把博客放在我的树莓派上后翻着 nginx 访问日志后让我惊讶的点是，还挺多人订阅我的博客的，也是见识到了各种订阅服务和
订阅器（甚至还看到有拿雷鸟来订阅的）。这也是给我这个周刊一点鼓舞吧，希望之后能写得更好点。另外就是之后可以多逛下其它
站点而不都依赖 Hacker News ，在自己写周刊后发现 [[https://www.ruanyifeng.com/blog/weekly/][科技爱好者周刊 - 阮一峰的网络日志]] 星期五出新的一篇的时候已经抢先
看了大半了，感觉好像科技类的周刊都在逮着 Hacker News 薅……

** 阅读
- [[https://web.archive.org/web/20030401192142/http://www.maillist.com.tw/maillist/home.htm][魅力站 - Wayback Machine]]: 在到处冲浪的时候也是看到了之前的一个电子报的服务，看起来之前有很多人
  搞过类似的周刊，可惜就是现在只能看个大概，里面的内容因为 web archive 并没有抓现在无法查看了…… 

- [[https://pomb.us/build-your-own-react/][Build your own React]]: 现在才了解到 JSX 这种在 js 写 XML 然后还要通过转译器转成正常 js 代码的操作，知道
  前端生态「疯狂」没想到是这么疯狂……

- [[https://kibty.town/blog/mintlify/][how to hack discord, vercel and more with one easy trick]]: 也叫，世界能有多草台，轻易之行任意代码然后甚至能读到
  服务下的 .env 文件。不过也算是了解到 svg 格式是能包含 onload, onerror 这种标签而执行 js 代码的，看起来之后做相关服务
  要把 svg 图片格式给拉黑了啊。

- [[https://noclip.website/][noclip]]: 一个线上电子游戏关卡博物馆，要做游戏设计的话这个网站肯定很有用，可以快速选择一个关卡然后自由浏览。

- [[https://news.ycombinator.com/item?id=46307306][Ask HN: Does anyone understand how Hacker News works? | Hacker News]]: 算是解释了挺多我对 HN 的疑问的，包括其组成、
运作方式等等等等，里面的金标准——好奇，确实是 HN 能够从 2006 年延续到现在的关键。

- [[https://pleasejusttryhtmx.com/][Please Just Fucking Try HTMX]]: 一个更加贴合 HTML 的脚本使用方式，在不想接受 React 之类框架的复杂度也是一个选择，不过对我
  这种来说还是更想在网站上写点 Lisp 用 SXML 来操作网页。

- [[https://armeet.bearblog.dev/becoming-the-machine/][Don't Become the Machine | Armeet Singh Jatyani]]: 嘿，是「老生常谈」的不要把自己当机器，不过确实，当人而
  不要当机器。

** Present day, Present time
年末了，除了周刊的总结还剩下博客年终总结和联邦宇宙年终总结……感觉还多事的，这三天时间搞得定吗？

