#+title: FoxThinking #9: 边缘行者
#+author: SouthFox
#+date: 2025-12-14 21:33:30
#+tags: FoxThinking

周刊第十期！没想到就已经第十期了，感觉写下第一期的场景已经迷迷糊糊了，但至少留下了一点文字，也算是这
个周刊的意义。我有点想对一段的时间内周刊做个总结，看看哪些事物发生了变化，但是创刊时定的试运行
为期三个月，那我就以一个季度来做为总结吧，刚好也能「顺带」把今年的年终总结写了。

,(read-more)

** 边缘行者的诞生
#+begin_quote
社会边缘人是社会学家罗伯特·E·帕克和埃弗里特·斯托内奎斯特首先提出的一个社会学概念，
以用来解释一个受两种文化影响的个体如何构建自己的身份认同。 [fn:1]
#+end_quote

「边缘人」很适合当社会学家，因为站在不同系统遍能更好地洞察各个系统 [fn:2] 。在这周再一次努力试图将两个系统「黏」合在一
起时惊讶发现在计算机领域我已经算是一个边缘行者了，看看我现在的所用的应用、环境、配置都不是单一的，都由不同的部分组成。例如
写这篇文章的编辑器是 Emacs 但实际用的是 Vim 的按键模式。原因单纯是当时对比了一下 Vim 和 Emacs 的相关资料数量，发现 
Vim 的资料比较多而 Emacs 也支持配置成 Vim 的模式就这么用下去了，没想到当时的选择竟深深影响到了现在。连日常用编辑器
都如此其它的就更是如此了，例如平常写点脚本我也更倾向于用 [[https://hylang.org/][Hy]] （在 Python 上的
一个 lisp 方言）或 Clojure （一个在 jvm 上的 lisp 方言）写；平常的系统用着 Arch Linux 但
实际今年开始就更多在和 Guix 打交道了；终端里用的多路复用工具是 Zellij 但平常用得最多的依然是 Tmux 的按键操作。

这种混用的方式给我带来了一种舒适，我可以保持一种开放的方式去调整和创造什么，但是困苦的也在于此，这种混杂非常
特化，我现在就算是用着 Vim 的按键操作但也会时不时的用着 M-x 然后调用几个 Emacs 上的命令；Zellij 按着 C-b 的 Tmux 操作
前缀也时不时按一些 Zellij 才有的快捷键。抵达这种状态所付出的努力也有点像是两头堵，想法很美好就是可以取个并集来集多家
之长但是在找资料学习的时候只会取到差集——很多时候还是空集，难以单纯套用一边的经验只好自己去慢慢摸索。而且说是取得了多家之长但我
很明显也是有侧重的，很容易在某个领域成为半吊子。我现在虽然知道如何 Vim 取括号里面的字符快速替换快速查找文本，但是连怎么
开启 Vim 行号显示都不知道…… [fn:3]

*** 蛋糕坯还是糖霜？
不过上面说得都的是一种类似杠杠想法，试图用一种小众领域去博取更大众领域优势的想法，这种论述之前就有人写
过详细的了（ [[https://dthompson.us/posts/lisp-icing-or-cake.html][Lisp: Icing or Cake? — dthompson]] ），选择做蛋糕坯还是做糖霜：做蛋糕坯更艰难但是最后会带来更大
的好处；做点糖霜能够直接带来回报但是会受限于底下的坯体。很明显，我这种实用主义拿来就用的懒狐最后还是选择做糖霜了。

** 阅读
- 《回到种子里去》：马尔克斯的杂文集，我还挺喜欢这种小杂文的，带上这本书在通勤之类的零碎时间随手一翻就能看，而且还不用强求
  一定是线性阅读翻到哪读那，这么说有点像是短视频。

- [[https://twobithistory.org/2018/12/18/rss.html][The Rise and Demise of RSS]]: 一个讲述 RSS 起源的文章。这周为博客加上了之前一直雪藏着的 Atom 格式的订阅源链接放在了侧边栏，
  还拿 [[https://www.rssboard.org/rss-validator/][校验器]] 检查了下我输出的 RSS 文件，发现存在的一些问题，包括时间格式和其中的一些 URL 带着没转义的空格
  和中文字符。时间的格式修改到了符合规范的格式，不过 URL 编码这个看了看有点难整所以先暂时推到未来再说了。好像从九月份转换博客框架
  以来输出的 RSS 文件就有点问题，现在纯靠各家订阅应用的解析器兜底，感觉有点尴尬……

- [[https://pagedout.institute/][Paged Out!]]: 一个由社区供稿的免费实验刊物，这种刊物的感觉让我回想起了关于报刊亭的时光，现在我还能想起买纸质刊物的时候就是在机场
  的书店里逛到然后买下的《博物》和《中国国家地理》，但是一年可能就那么一两次。还是挺怀念这种刊物感的，这也是我现在写周刊的原因吧……不
  过用心程度和 Paged Out 这种就没法比了，我想之后可以向这种刊物能多学习。

** Present day, Present time
这周终于也是把树莓派的博文给写出来了（ [[/2025/12/does-the-fox-eat-raspberry-pi/][狐狸会喜欢树莓做的派吗？树莓派鼓捣记]] ），可喜可贺可喜可贺。

这周同时还在搞的项目是一个针对
[[https://curiositystream.com][curiosity stream]] 的代替前端，因为这周查阅邮件的时候发现已经快要到续费的时候了。今年这个流媒体平台看的不多，主要原因是在 PC 端
上观影体验不佳看的影片清晰度一直很低，但安卓 APP 是正常的。排查了一下发现是网页端的播放器用的 dash 播放器一直锁不住清晰度
,原因是 dash 协议会自动推测网络速度而自动选择清晰度而我的网络测速不佳（但实际还是有速度的）然后导致 curiosity stream
的播放器一直在锁定在低清晰度。然后我就一时兴起了抓取了一下 api 解析出视频地址然后丢到 [[https://dashjs.org/][dashjs]] 这个播放器里发现
直接能跑 2K 清晰度的，于是就更加兴起了想把整个的逻辑理顺，也是因为选择的 [[https://lips.js.org/][lips]] 这个在 javascript 上构
建 scheme lisp 的库（啊，又是糖霜，这就是在主题部分说的将两个系统「黏」合在一起的项目）比较「好玩」所以现在正在努力把玩中。
也是实在体验到了前端开发的乐趣，一种这里鼓捣那里鼓捣微调然后马上去刷新页面检查效果的投入感……希望能在下周鼓捣
到基本能用吧。当然，curiosity stream 的费用还是续了，毕竟能够方便找到纪录片的平台不多，一边看纪录片
一边学外语，两件快乐事情重合在一起。而这两份快乐，又给我带来更多的快乐……

** 脚注
[fn:1] [[https://zh.wikipedia.org/zh-cn/%E7%A4%BE%E6%9C%83%E9%82%8A%E7%B7%A3%E4%BA%BA][社会边缘人 - 维基百科，自由的百科全书]]

[fn:2] 上野千鹤子. 从提问到输出. 文汇出版社, 2024, 第 9 页.

[fn:3] 搜了下是 =:set nu=
