#+title: FoxThinking #8: 守住八分地
#+author: SouthFox
#+date: 2025-12-07 20:04:55
#+tags: FoxThinking

百分之八十的资源只会在百分之二十手上：论文引用数量、代码中的错误数量、地震的震级情况、人们的财富分布，这没有什么稀奇的，这
就是一个支配着世界的一个规律，幂律定律（或者叫二八定律）。

,(read-more)

** 不「正常」的二八
不过幂律定律其实不是在什么领域都见得到，它一般是在一些不「正常」概率分布中会显现，这里的正常指的是「正态分布」（
 normal distribution ）。生活中很多都是正态分布，例如抛硬币扔骰子在次数越来越多时分布图里最显眼的一定是 50/50 和
点数为六的情况。其它的例如统计人的身高、气温平均值就会发现总会出现一个非常突出的平均值和其它少见的极端情况，这就是
正常的「正态分布」。那么不正常的情况就是例如财富分布、地球上国家的国土分布，这些领域中总是有出现跨越很多个
数量级的巨无霸，而且一般整体的数据会给这些巨无霸给吃完达到一种「百分之八十的资源只会在百分之二十手上」的效果。

这两种事件的概率分布也可以叫做轻尾分布和长（重）尾分布，对这两个概率分布为的简单定义是当分布中取一个很大值的时候，找到一
个更大值的概率高不高 [fn:1] ：

如果不高例如人的身高（当有一个两米三的人找到比 ta 高的人概率还大吗？那两米四呢？）、气温（在五十度气温时找到比这天气温还
高的概率还大吗？），就是轻尾分布，造成的数据是聚集和有界的；

如果很高，例如个人财富、国家人口数量和土地，那么就是长尾分布，造成的数据会横跨几个数量级，而且样本数据会被超大数量样本主导。

因为塑造这两种背后的力量是不同的，轻尾分布的是加法，而塑造长尾分布的是乘法（通常还是基于已有样本比值例如钱生钱和大国人口
增长） [fn:2] 。

** 互联网中的无足轻重的百分之八十
毫无疑问互联网也在幂率定律的支配下，百分之八十的资源都集中在那几家巨头上，重来几次互联网的发展过程互联网可能叫得上号的网站
名称会变但数量很可能仍是这个数量。这意味着对种情况就没有什么「对策」了吗？现在我只能在这些巨头上流转只能在推荐算法的胜利
的阴影下遵从平台的意志了吗？

不，哪怕是一个玫瑰色回忆 [fn:3] ，我仍然还是怀念之前在互联网上「冲浪」时候的发现一些新奇的个人网站的快乐，而不是检点推荐流
上的消息感到自己像是一些什么格子间内「牲畜」。在幂律定律下除了令人显眼的百分之八十还有一个侧面就是「自组织临界性」
（ Self-organized criticality ），在幂律定律支配下的系统例如雪坡或森林，当达到一个临界状态时，就无法判断一个小小的事件
会带来怎么样的后果了，这格小小的事件可能会在整个系统中互相感应不停传播造成一个风暴，或许大概率只是一点点的雪花落下或是为一两棵树
带来焦黄，但也有可能是整个雪坡的滑落或是要将整个森林吞没的百年难遇的火灾 [fn:4] 。

虽然我建立的只是些很小的站点，写的只是一些没什么营养的内容，是在这个体系下微不足道的百分之八十的一部分，但我还是打算存在下去。
我不奢求成为引爆点将一大串的关注聚焦在我这里或是去推动些什么，只是希望这里的存在可以让互联网更……健康。在现在不断极化的互联网
里，也是重新捡起个人站点、网络日志的时候了，发出自己声音，维护好自己的「八分地」。

** 阅读
- [[https://mp.weixin.qq.com/s/X6lIy0uO2WMuFZUATY958Q][谁在给你的脑子“投毒”？]]
  #+begin_quote
  PPT上有一行醒目的红字，“目前我已经为您做到：全自动采集、全自动改写、全自动发布！”
  
  公司里电脑数量比员工更多，大部分房间都用来放电脑。公司对外的PPT上还展示了公司的“手机墙”，28部放在架子上的手机，都在开机自动运行程序。
  #+end_quote
  
  大模型就像一条强劲的泥鳅，把水搅浑。凭借这个「词语机器」运营们正在疯狂「穷举」关键词的组合试图去寻找爆点，已经信无可信。
  
- [[https://tonyalicea.dev/blog/were-losing-our-voice-to-llms/][We're Losing Our Voice to LLMs | Tony Alicea]]
  发出自己的声音，就算不成熟也可以通过练习去磨练。

- [[https://www.solidot.org/story?sid=82752][奇客Solidot | Meta 靠诈骗广告收入去资助 AI]]
  #+begin_quote
  Meta 不愿意立即删除骗子的账户，允许“高价值账户”积累逾 500 次违规，骗子的违规记录越多 Meta 收取的广告费率越高
  #+end_quote
  
  惊讶吗？不惊讶。成为「黑箱」的平台最可怕，作恶只是一个在已经放上千钧重的砝码天平稍微掂量几下就作出的决定。

- [[https://www.infoq.cn/article/uxW0pGp9AjP3szECYjAO][新任CTO把PHP换成Perl，导致成本飙升错失市场机遇！网友：别怪技术，问题出在人身上_编程语言_李冬梅_InfoQ精选文章]]
  #+begin_quote
  当非核心信念受到质疑时，大脑推理中枢正常运转。参与者能够理性分析证据，权衡论点，甚至改变原有看法。
  然而当核心信念遭遇挑战时，大脑反应如同遭受物理攻击。负责威胁识别的杏仁核立即激活——这与遭遇猛兽时的应激反应如出一辙；处理情绪痛苦与厌恶的脑岛皮层剧烈活动；最具启示性的是，维持自我认知的默认模式网络会立即进入防御状态，全力守护既存身份认同而非评估新信息。
  #+end_quote

  - [[https://jandan.net/p/121573][你的身体以为你每天都在逃命 - 煎蛋]]
    #+begin_quote
    人类学家发现：现代生活把我们逼成了“每天面对狮子”的状态。身体以为还在非洲草原，随时得搏命逃跑，可狮子永远不走，导致慢性压力把健康一点点耗干。
    #+end_quote

    战斗或逃跑这也是个很常见的「迷思」了，不过确实也没想到计科领域里编程语言（或编辑器）战争会牵扯到这些，确实有时候也没必
    要「自找没趣」去挑战人的「立身之本」啊……

** Present day, Present time
这周从感冒中回复稍微好点了，虽然睡眠周期依然很「怪异」，工作日睡眠时间在六个小时左右然后周末就直接兽性大发在十二小时左右同时依然很困顿，
没有什么精力。看起来得考虑一下寻找一下睡得更好的 SOP 了，我想应该还是跟光照有关，看看多出去走走多见见光会不会对睡眠有所帮助。

** 脚注
[fn:1] [[https://zh.wikipedia.org/zh-cn/%E9%87%8D%E5%B0%BE%E5%88%86%E5%B8%83][重尾分布 - 维基百科，自由的百科全书]]

[fn:2] [[https://www.bilibili.com/video/BV15kj4z4Eju/][【漫士】世界是对数的……吗？为什么？ - 哔哩哔哩]]

[fn:3] [[https://en.wikipedia.org/wiki/Rosy_retrospection][Rosy retrospection - Wikipedia]]

[fn:4] [[https://www.youtube.com/watch?v=HBluLfX2F_k][You've (Likely) Been Playing The Game of Life Wrong - YouTube]]
