#+title: FoxThinking #7: 无限猴子与刍狗
#+author: SouthFox
#+date: 2025-11-30 21:20:09
#+tags: FoxThinking:书籍:科学

生命多是多么离奇和复杂啊，哪怕一个血红蛋白的复杂程度，就像是一个猴子在打字机上随机打字到要「碰巧」
打出一首十四行诗一样。这里蕴含的可能性已经比整个可观测宇宙里的原子数量一样多了，现有的科学理论可
很难解释生命产生的复杂性啊……或者，真是这样吗？

,(read-more)

** 猴子式生命
#+begin_quote
他非常倚赖一个我们或许可以称之为“我就是不能相信”的论证……
……似乎无法以达尔文的理论解释……并不容易解释……难以了解……不容易理解……我发现它不容易理解……
我发现不容易了解……我发现难以理解…… [fn:1]
#+end_quote

这种「想当然」的模式看得多了也就乏了，拿生命的复杂度来说，其实没有考虑到生命是一个继往开来的「过程」，生命从来不需要
个体单打独斗，不需要一开始就是《哈姆雷特》。哪怕一开始打出来的全都是锟斤拷烫烫烫的语句也没关系，只要能要求后续猴子不是
随机打而是要造着原文去复制（虽然不是很猴子）然后存在下来。在这里的情景中如果将目标定位《哈姆雷特》，那么在一次次的复制
传播中的微小突变（这很猴子）中，筛去变得更不像《哈姆雷特》的，留下更像的，那么将会看到这个打出来的作品在慢慢往《哈姆雷特》
靠拢。

** 刍狗式生命
#+begin_quote
天地不仁，以万物为刍狗。
#+end_quote

天地没有仁心，把万物当作祭祀用的刍狗：在祭祀时顶礼膜拜，祭祀后却不屑一顾甚至拆开来当燃料。天地对万物的其实就
像一个筛子，通过合适的留下不合适的。这种「意志」的体现甚至不需要什么「意识」，甚至可以说是物理规律，例如海边的圆滑的
石子甚至是 3D 打印的螺丝分类器（[[https://www.youtube.com/watch?v=fZ7rdNYJmZ4][3D printed screw length sorter - YouTube]] )。

所以生命就像是无限个猴子在有限台打字机上打出刍狗然后期待是在祭祀时节能够多打一点（什么硬凑的比喻）。

** 阅读
- 《盲眼的钟表匠》：天择不为未来打算，没有视野，没有现将。如果天择是自然界的钟表匠，它一定是个盲眼的钟表匠。
  有点想把《物种起源》和理查德·道金斯的作品都翻出来成体系的读一读了，因为这是现代人在不去学习前置专业知识上能够读到的生物科学
  著作了……

- 《中国建筑史》：收集兴趣之，建筑——但是其实没有什么兴趣，就像书中说的：中国建筑以木料为主要构材，在用石上是失败的 [fn:2] ：
  而在我的整个成长过程中根本没有什么木质建筑的参与，只有盒子壮的钢筋混凝土盒子，所以自然没什么感触和兴趣了。里面的历史
  资料部分倒是读得下，一种眼看他起高楼又眼看他楼塌了的朝代更替。

** 观影
- 《疯狂动物城2》：没想到竟然已经块十年过去了……但味还是那个味，感觉有点像三年后应该就做出来的只是拖到了现在，隐喻和映射依然
  刻板和直接但是动物所以看起来就没问题。不过不得不说这个电影的号召力真强啊，我在附近没什么客流量的小影院都能达到七八十的上座
  率。
  
** Present day, Present time
这周的空余时间都拿来「吃派」了，现在这个博客不出意外就用树莓派通过 Cloudflare Tunnel 提供内容了，访问速度其实还行，比 Github
Pages 的访问速度要快一点，后续为了高可用还需折腾一下健康检查然后切换到 Cloudflare Pages 服务的配置。搞好之后应该就拿搭建的
服务和相关配置拿来写篇文章吧。

另外就是不要碰高糖饮料了，一瓶统一阿萨姆奶茶直接把我干到涕水横流了难受的很。想了想现在我的健康状态很微妙，公共交通的通勤堆积了很
多病毒，平常相安无事只要喝点高糖饮料和受点寒平衡立马打破身子立马遭殃……在无法改变依赖公共交通的情况下还是少吃点高糖食品然后坚守一下
「健康」的作息吧。

** 脚注
[fn:1] 理查德·道金斯. 盲眼钟表匠. 中信出版集团. 2014.

[fn:1] 梁思成. 中国建筑史. 台海出版社. 2023, 第 11 页.
