#+title: FoxThinking #6: 珍视是最大的浪费 
#+author: SouthFox
#+date: 2025-11-23 23:21:10
#+tags: FoxThinking:读后感

珍视有时候也是一种浪费

,(read-more)

** 空闲之于浪费
双十一时买了树莓派 5 8G 版本和一个 2T 的固态硬盘，在一开始买的转接板过小之后又买额外买了个合适的转接板。
这一周的空闲时间都花在了折腾树莓派上，为了创建需求翻了很多相关帖子：《树莓派不吃灰的xx用途》、《树莓派最
佳项目》、《我用树莓派干了xx》……最后挑选用 calibre 建立自己的书籍库存一些在 [[www.humblebundle.com/][Humble Bundle]] 上买的书
(最后统计下来发现竟然买了差不多一百本了）。calibre 官方不建议将数据库文件放在网络存储上，然后我也不想把
calibre 整体放在树莓派上。看来看去发现我可以将所有文件复制到树莓派上然后用 [[https://github.com/janeczku/calibre-web][calibre-web]] 项目作为一个前
端进行展示。不过这意味着我需要在我的电脑存上一份然后在树莓派存上一份，但这意味需要消耗多份空间，值得吗？
最后统计出来其实我所有相关的书放在 calibre 里也就消耗 1G 的空间，这点空间哪怕对于我笔记本的 1T 空间
来说也就千分之一（对于树莓派来说就二千分之一了），按照一个 epub 的电子书文件 10M 空间来算其实也能存很多
了。

之后检查了一下我的笔记本，除去 .gradle 和安卓 sdk 之类的构件依赖和缓存，我这 1T 电脑大半年下来其实也就用了
30G 的空间，按照这个趋势哪怕用上十年也只会用上 300 多 G 的空间。这么节省的用法「得益」于我之前用得设备空间都不大的缘故，
所以不知怎么就养成了能在线看的就在线看、不轻易插入媒体文件之类节省存储空间「小妙招」。但现在其实已经没必要
这么做了，有点让我想起以前买的本子和纸张因为太「新」而不轻易落笔之后在整理时在灰尘堆里翻出来的经历。有时候「珍视
就是一种最大的浪费」而且「过早优化是万恶之源」。所以很多东西还是先「用上」等到了一定程度才来考虑下一步。

** 阅读
- 《傲慢与偏见》：有时候名著是时间这一个「大过滤器」最直观的体现，或者说可以把名著看成历史长河上的「高分榜单」，虽然
  不一定适合但一定有质量，所以还是来多看点名著吧。《傲慢与偏见》这本书虽然之事描写了三五户人家的家长里短之事，但里
  头的杰出之处比起其它名著也丝毫不少，我认为里头最有价值的就是所谓的「为人处世」之道：

  - 有时候人得要「装」：虽然很多时候有个性不随波逐流超脱于人是件好事，但是有智慧的人不会给自己找麻烦事，而「礼数」
    在处事时可能是最能减少麻烦事的一个「投入」了。书里头如果达西能像彬格莱一样能够待人和善热情一点能省下多少后来的
    麻烦事啊！书里头很多里都在描述交际的时候面对不喜欢或麻烦之人如何如何，哪怕不喜欢，搪塞和敷衍上说几句客套话
    不要结恶，这也是一种避免麻烦事的体现。可能对于神经多样性 [fn:1] 的人来说很难，不过「说话多盯着人眼睛」、「表现
    得诚恳一点」、「多思考接下来要说出口的话会引起他人怎么样的反应」这些能尽量去做到吧。

  - 偏见是个坏东西：作为标题的一部分偏见在书里有众多描述，除了最直接的伊丽莎白对达西的偏见其实还有人对自己的偏见，伊丽
    莎白自以为有知人之明有本领的「偏见」也带来了对达西的「偏见」。所以有时候人还是需要一个手段检阅自己的想法思考思考它
    到底是否受到了偏见影响吧……嗯，之后的日记多写点这方面的吧。

- [[http://landoflisp.com/][land of lisp]] （HTTP 网站警告！）:好「癫」的一部作品，这本书作为 [[www.humblebundle.com/][Humble Bundle]] 之前一个捆绑包里的物品现在整理时
  才发现，看了看它的官方网站其实做的很有趣的，也让我见识到了十五年前的前端生态包括 jquery 还有针对 IE 浏览器的优化。
  现在我动了汉化它的心思然后挑一个 lisp 的 web 实现来复刻网站上的点击效果（其实我博客现在也是一个 lisp 之地了，百分之
  九十都是 lisp）。
  
** Present day, Present time
是的因为这周的时间都花在折腾树莓派上所以其它的流程没怎么管，我还在寻找属于我的「启动流程」，因为很多时候我还是能干事的只
不过我很多时候是败在「点进来」这个动作上，所以还是多思考如何启动吧！而且很多时候也要考虑记录笔记之类的是阶段性的，应该多
多及时记录而不是等待最后的总结复盘，否则到了最后债多了不愁就没有然后了。

** 脚注
[fn:1] 孤独症（自闭症）、AD(H)D 等一系列偏离「平均」模式的人的说法……
