#+title: FoxThinking #23: Q1报告
#+author: SouthFox
#+date: 2026-03-29 21:55:08
#+tags: FoxThinking

03月29日，某个不知名 FoxThinking 周刊（下称「本周刊」）发布第一季度报告。本季度，本周
刊实现的「满足创作者的创作欲」的满意程度同比小幅上升；访问量因创作者懒得分析（本站点放在创作
者树莓派上由 Nginx 提供服务，还是能记录到访问记录的）无法发出；本季度，为应对更加激烈
的 LLM 狂潮，本周刊对相关话题讨论度有所上升。

“面对社会环境变化，我开始有点厌倦相关讨论开始觉得太阳底下无新鲜事了”本周刊创作者表示，
“天哪能不能让我逃开这绝望的轮回，要不还是向古代或什么处于剧烈变化时代哲学家索求慰籍这样可
能更好点吧”。

,(read-more)

** 分析
好了，扮公司游戏该结束了，还是来遵照之前决定对这个季度周刊进行分析：

- [[/2026/01/fox-thinking-12/][FoxThinking #12: 发现身边的「怪物」]]：里面提到的我想当个娱乐/消遣程序员（recreational
  programmer)我仍在继续。
- [[/2026/01/fox-thinking-13/][FoxThinking #13: 节气差异]]和[[/2026/02/fox-thinking-17/][FoxThinking #17: 想想春天的速度]]：总有一天，我能完善这些个零散小脚本
  扔到树莓派上辅助我感受这个世界，总有一天……
- [[/2026/01/fox-thinking-14/][FoxThinking #14: 我好像没那么在乎「最佳实践」了]]和[[/2026/02/fox-thinking-19/][FoxThinking #19: 不要恐惧]]：这就是我所说的对相关话
  题讨论。
- [[/2026/01/fox-thinking-15/][FoxThinking #15: I build this city]]: 相关的评论系统项目仍在进行，构思得已差不多了，只等我把时间片分到
  这个项目上……
- [[/2026/02/fox-thinking-16/][FoxThinking #16: 信息毒害胆怯]]：我现在就是等 RSS 阅读器里攒了几天在统一看掉，每次刷到一个热点事件的最
  新回应就感觉还是……蛮有「乐子」的？而且我发现这种信息摄入方式确实更令我平静了，可能是给了我「没有什么事是不能
  先停一停看看后续发展」的印象吧。
- [[/2026/02/fox-thinking-18/][FoxThinking #18: 除夕]]：新的一年但不是新的我，怎么才过去一个多月，当时过年觉得我就在当下的感觉现在想来就已经
  模糊不清了呢？
- [[/2026/03/fox-thinking-20/][FoxThinking #20: 回看来路]]：对自建这个领域的感叹，如果让现在的我和之前刚接触到自建这个领域的我进行对话，现在的我应该
  会被评价为「好酷」吧。
- [[/2026/03/fox-thinking-21/][FoxThinking #21: 如何将用户「拉下水」]]：当接触越来越多能轻松设置 Hook 和替换掉执行流程的 Emacs 包后，就越对
  只能切换点配置的应用感到沮丧。
- [[/2026/03/fox-thinking-22/][FoxThinking #22: 逆炼摩尔定律]]：相关的项目仍在推进……只待我把时间……片……

然后是呼应上次总结[[/2025/12/fox-thinking-11/][FoxThinking #11: 季度总结]]，这个季度的「阅读」板块不是从 HN 摘出来的链接多了点，参杂了一些心理学、社会
科学、生物学等内容，对此我为这个状态而感到喜悦。有点期待下个季度相关的阅读会不会更多样化，或许会出现些文学相关内容，毕竟我可
是杂食狐啊。

** 博客
想了想还是想记下对博客的更改，单开篇博文我觉得没必要，新建个单独页面我又太懒，那就索性放到这里吧。

最明显的侧边栏变化首先是增加了两个 Web Ring ，一个是 [[https://xn--sr8hvo.ws/][IndieWeb Webring]] ，另一个是 [[https://fediring.net/][Fediring]] ，两个都是发现有趣站点
的好地方。其次是对于字体配置和主题配置配置栏，因为要实现带状态的切换不可避免要出现一点 js （不过至少使用 lisp 写的），对
于 noscript 环境，现在是回落到「白底黑字」的简单站点，后续看看还有没有什么更好的方法吧。
主题部分也是在这周刚增加了个 [[https://aesthetics.fandom.com/zh/wiki/Frutiger_Aero][Frutiger Aero]] 主题。比起 386 风格，这种 Win7 毛玻璃配上绿水青山蓝天白云的风格是我真实经
历过的，当时我搓玩后在浏览器看着预览效果直接楞了会神……

然后是博客的底层功能，一月末的时候整体重构了下将相关代码拆成模块，为后续加入新功能的加入打下了基础，比如这个月加入了个反
链功能就很轻松，尤其是我掌握着全流程能直接操作语法树而不用面对成品 HTML 文件，直接简单提出来链接放到一张哈希表就好了，半天
时间就搞完了，之前在 Hugo 上实现相同的功能可让我抓耳挠腮了好几天。也是因为现在有了反链功能，对提及之前的文章也是更肆无忌惮了
些，例如这篇季度总结。

相关 org mode 解析器也完善了下 blockquote 解析和新增了 example 语法解析，然后也顺应给语法解析模块补上了单元
测试（这博客搞半天还要自己拼啊！），可能再过几个季度这个 org mode 解析器就能「正式」支持 org mode 了吧……

** 阅读
发现其实我对于相关的链接非常「剑走偏锋」，不会像其它周刊要么只给链接要么先概述文章内容再阐述些什么，我一般都是直接阐述自
己的想法的。似乎是有点受 HN 影响，毕竟在 HN 上评论默认评论是要先看了原文的，所以我在这就会默认读者已经读过。我就不纠结
这到底算不算好的做法了，毕竟，嘿，这个刊物就叫做 FoxThinking 呢。

*** [[https://dbushell.com/2026/01/09/death-to-scroll-fade/][Death to Scroll Fade! – David Bushell – Web Dev (UK)]]
这个文字效果，非常 Hexo 上 [[https://github.com/theme-next/hexo-theme-next][Next]] 主题既视感，每次等文字效果弹完我都感觉一大劫都过去了。不过话说现在独立博
客 Next 主题风潮已经过去了啊，现在迎面走来的是……[[https://github.com/anzhiyu-c/hexo-theme-anzhiyu][安知鱼]]吗？天哪这也是个要人苦等的配置，在网络不佳的话等文章加载
屏幕走完感觉要度过一个无量劫那么长的时间。

这也是我哪怕这个站点已经够花里胡哨有点风格先行压过读者阅读体验（现在倒是加了字体选单配置）也不在动画上做更多了，毕竟是真
得： Please don’t 。

*** [[https://nautil.us/how-tiny-shortcuts-are-poisoning-science-1279176][How ‘Tiny Shortcuts’ Are Poisoning Science]]
科学家已经成为凡人，更成体系学术界带来的压力也让科学家们在泥潭上行走，面对压力，科学家们不得不「你这里的数据有点问
题，所以我用 PS 修了下」。科学家的事怎么能算造假呢？这叫美化！

*** [[https://unterwaditzer.net/2025/codeberg.html][Moving from GitHub to Codeberg, for lazy people - Markus Unterwaditzer]]
这里的思考是，[[https://codeberg.org/][Codeberg]] 是只用来托管自由软件的，所以在 Codeberg 上托管私人站点（博客、笔记）来说， Codeberg 方面会觉
得有点……不爽 [fn:1] ? 毕竟总有人要得给基础设施付钱或精力 [fn:2] 。所以其实 Codeberg 并不合适任何人，如果有想远
离 GitHub 又想贴近之前用 GitHub 体验托管仓库的话，可能现在比较好的方式就是自建 [[https://forgejo.org/][Forgejo]] 了吧。

相关文章： [[https://rz01.org/eu-migration/][Migrating to the EU - rz01.org]]

*** [[https://cn.nytimes.com/opinion/20260327/economy-attitudes-republicans-democrats/dual/][美国如此富有，为何美国人却如此痛苦 - 纽约时报中文网]]
在一个有「有贵宾钥匙登机、预登机和另外九个登机组」的国家，钱是资粮、是安全网、
是最终幻想，有钱就能享受最好的服务。如果是没那么有钱的人，看着比他「高一级」的有钱人或是顶级有钱人而感到焦虑。是的，比较
是幸福的小偷，而美国这个环境可以说是：「苦其食，愁其服，危其居，忧其俗。阶层相望，骂街之声相闻，民至老死，继往
开来。」 [fn:3]

*** [[https://blogs.windows.com/windows-insider/2026/03/20/our-commitment-to-windows-quality/][Our commitment to Windows quality | Windows Insider Blog]]
挺好的就是来得太晚了，我觉得要不微软你们把钱投到 [[https://www.winehq.org/][Wine]] 项目得了？

*** [[https://www.sciencealert.com/worlds-longest-study-on-happiness-still-going-strong-after-88-years][World's Longest Study on Happiness Still Going Strong After 88 Years : Scienc...]]
太长不看，让人幸福的最重要是「联系」。

虽然哈佛这个幸福研究有太「西化」之嫌，但真的，我真的好奇到底能进行到哪一步啊……

*** [[https://daily.zhihu.com/story/9788669][是奴隶主养活了奴隶，还是奴隶养活了奴隶主？ 知乎日报]]
既视感，发动！

*** [[https://citiesandmemory.com/obsolete-sounds/][Obsolete Sounds]]
真酷啊。

*** LLM
**** [[https://lucumr.pocoo.org/2026/3/20/some-things-just-take-time/][Some Things Just Take Time | Armin Ronacher's Thoughts and Writings]]
每次看到讨论场上关于 LLM 快速生成代码巴拉巴拉的言论我就狐疑：发出观点的到底是不是实际写代码的？代码不是资产，它是
债务。而且真把代码当成资产， LLM 像老虎机似生成代码就像彩票中奖飞来横财一样，最后是守不住的。 [fn:4]

**** [[https://shkspr.mobi/blog/2026/03/im-ok-being-left-behind-thanks/][I’m OK being left behind, thanks! – Terence Eden’s Blog]]
就……只是，等等也无妨。

**** [[https://it-notes.dragas.net/2026/03/20/enshittifaication/][EnshittifAIcation - IT Notes]]
比 Agent 泛滥更恐怖的是人成了 LLM 的 Agent 。

** Present day, Present time
每次写到最后这里就无力气写下去了然后就潦草收尾，所以这个板块还要保留吗？或者说我真该把写作摊分到每天来写而不是
在一个晚上狂暴写完？

** 脚注
[fn:1] [[https://docs.codeberg.org/getting-started/faq/#how-about-private-repositories%3F][Frequently Asked Questions - How about private repositories? | Codeberg Documentation]]

[fn:2] codeberg 时不时因为底层 ceph 存储宕机或停机维护，我能理解……

[fn:3] 化用自老子《道德经》通行本第八十篇（或帛书本第三十篇？）

[fn:4] [[https://theconversation.com/how-winning-1-54-billion-in-mega-millions-could-still-lead-to-bankruptcy-105275][How winning $1.54 billion in Mega Millions could still lead to bankruptcy]]
