#+title: FoxThinking #20: 回看来路
#+author: SouthFox
#+date: 2026-03-02 23:59:59
#+tags: FoxThinking

在下班通勤时间想到：在自建（自托管）这方面我到底是从什么时候开始的？

,(read-more)

仔细想想是十年前的事了，那个时候我就热衷于下载点网上不知名的托管站的压缩包解压什么 asp 网站代码然后放
到 IIS （是的，十年前我还用着微软操作系统）上本地看看效果了。然后是一些提供免费空间的托管商（类似现在
的 pages 服务），折腾了一些博客、论坛系统后不尽性开始拿安卓手机上的 [[https://www.kslabs.ru/][KSWEB]] 应用（里面捆绑了 Nginx, Mysql,
PHP 等一众运行环境，可能）来折腾 Word Press 服务。一边折腾一边想着当开个热点形成个小局域网当有人连上后就能
访问我的网页了，还是挺酷的。

不过再半年多后就还是有点受不了手机上的服务，开始购入一个云服务器在上面实际运行 Wordpress ，本博客的第一篇
文章（ [[/2018/06/世界，您好！/][世界，您好！]] ）应该就是在这个时候产生的。沾上服务器后续就是显而易见去折腾更多自建服务，最近重建相关
服务发现已经差不多二十个服务在部署了，也是挺能折腾的。以前想在能自己实际接触到物理设备上提供网站服务的想法
现在通过树莓派（ [[/2025/12/does-the-fox-eat-raspberry-pi/][狐狸会喜欢树莓做的派吗？树莓派鼓捣记]] ）达成了，如果不意外的话，现在展示的这个网页应该就是
由我的树莓派提供内容的。可惜因为家庭宽带的网络复杂度现在是由 cloudflare 的隧道服务提供访问，希望在后面能找
到不依赖专用服务的办法提供网页吧。

** 阅读
*** [[https://rsdoiel.github.io/blog/2026/02/21/a_simple_web_we_own.html][A simple web we own — Robert's ramblings]]
经常想不到互联网不是建在虚空上的，访问一个网站就相当于知道一个地址然后前往这个地址，如果有道路那么不论是坐
车骑马走路还是游过去那么肯定就能到达。一个超级数据中心就是繁华的都市，一个放在茶几上的树莓派就是偏远的城郊。

随着静态网站生成器的兴起和相关 HTTP 服务器软件的持续优化，现在托管一个网站真得很简单了，虽然对非技术人士
来说新掌握的概念确实有点太多了，希望之后相关的流程能再优化优化，达到想建站之人终能建。

*** [[https://hackernews.love/][Every great project was once called a bad idea]]
哈哈，我要看到血流成河。不过这个网站感觉有点泛泛而谈，而且有些列出来的帖子确实算是产品中实在的问题，
看向 [[https://news.ycombinator.com/item?id=47120188][Hacker News.love – 22 projects Hacker News didn't love | Hacker News]] 上的讨论，嗯，果然有人
跟我持有相同的想法。

*** [[https://clojure.org/news/2026/02/18/state-of-clojure-2025][Clojure - State of Clojure 2025 Results]]
2025 年 clojrue 生态调查报告，感觉 clojure 社区确实有点说法的，例如作为搭建在 jvm 上的语言，问到不能
用 clojure 后，只有 11.40% 的人会转向用 java ，差点让 python 的 10.09% 超了，也是一种耐人寻味的现
象了。

*** [[https://blog.cleancoder.com/uncle-bob/2019/08/22/WhyClojure.html][Why Clojure? - Clean Coder Blog]]
又一篇 Why Clojure 文章，但是在 2019 年这个 LLM 还没席卷全网的时候写的，看起来甚至有点新鲜，因为没有参杂这方
面的讨论。不过说得没错， Lisp 拒绝就此死去，就像那只街区上烦人的流浪猫一样，它总会回来的。

*** [[https://hacks.mozilla.org/2026/02/goodbye-innerhtml-hello-sethtml-stronger-xss-protection-in-firefox-148/][Goodbye innerHTML, Hello setHTML: Stronger XSS Protection in Firefox 148]]
新的设置 SetHTML 方法，可以帮忙缓解 XSS 攻击。只是如果对于有执行风险的数据，最好的方式是能将其区别对待，
没错，就是用 Lisp 表示网页元素让标签就是标签，内容是内容。

*** [[https://keepandroidopen.org/][Keep Android Open]]
安卓还有半年就要求只有注册过的开发者才能为安卓平台开发 APP ，很糟糕，如果真到了自己都安装不了自己开发的应用的话，
可能真得考虑刷机或者 Linux 移动设备项目了……
*** [[https://maplant.com/2026-02-09-I-Wrote-a-Scheme-in-2025.html][I Wrote a Scheme in 2025]]
真酷啊，在失业后将自己的精力浇灌在兴趣项目上，最后得到了这样的回报。嗯，不过这也是个机会，撬动 Rust 生态
的机会，可能当我玩得开心的时候我就顺带把 Rust 给学了吧。

*** 大模型相关
**** [[https://blog.codemine.be/posts/2026/20260222-be-quiet/][HUMAN=true]]
当使用编程 agent 编码时，写下一个个 markdown 提示文件、贴上一条条 env 环境记录、关闭一段段控制台输出，
到了最后，或许之后会要求开发者应用中内置 =LLM=true= 来做到这一点吧……

**** [[https://keleshev.com/ai-equals-true-is-an-anti-pattern][AI=true is an Anti-Pattern]]
是吗？但其实仔细一想，写下精准的功能阐述和功能约束……不就是 =README.md= 应该做的吗？让控制台的输出不要
那么多为什么考虑 =--quiet= 这个参数呢？为了 LLM 方便的做法，其实本身就是要在面向人类就要做到的。

** Present day, Present time
春节假期回来只有单休的一周，勉强维护点结构性，这几周也是成功把在运维上的事给搞定了，接下来就该干点有
创造性的事了。
