#+title: 对着虚空咕哝
#+author: SouthFox
#+date: 2026-03-15 23:33:43
#+feed-only: t
#+tags: 日常

新年新气象，但是首周单休然后下一周身体还有点不适，让我感觉没什么精力去做什么。不过这一周希望我
能回到正轨上，只是这个想法对于我这种内存有点吃紧的 ADHD 特质人来说还是太有挑战性了。

说到 ADHD ，现在仍只是处于「天哪，这简直是我」的阶段，之后可以找个时间尝试用抽离的姿态翻看
之前的日记看能找到些什么，也可以向亲友询问找补下发育史。不过我想最重要的还是保持睡眠？毕竟这两周
的日均睡眠时间只有七小时，还是有点欠睡眠账的。我的 ADHD 表现很多时候就是脑子的后台任务开太多了（不管
是潜意识中还是显意识中的）然后碰上睡眠不足的这个相当于往「内存」塞了很多垃圾碎片的情况，走神的情况
就更糟糕了。

说到日记，我现在的日记也只是处于每天打开 [[https://www.orgroam.com/][Org-roam]] 的今日节点然后随手
写一点的程度，没什么不好，但或许我应该更能撬动一点这里的力量？首先想到的就是应该有个限制而不随心所欲的想到什么
就写什么 [fn:1] ，然后想到或许我可以参照 [[https://mindthenerd.com/the-socratic-journal-method-a-simple-journaling-method-that-actually-works/][The Socratic Journal Method]] 的办法来做，看了一下似乎并不是很
难（突然想到这是否就是生活意义上的导入库来用），而且也很方便跟感恩日记 [fn:2] 联动，有结构性的框架对
于有 ADHD 特质的我应该有所帮助（而且也不是很难办，在我的 emacs 里配置加点参数就……）。希望能够凭借这个流程
理清我内心真正的忧虑与关切。

说到忧虑的事，虽然我觉得我还年轻但实际上是我出来工作的第三个年头了，哇哦，写到这我已经有点恍然了，不敢相信当时我就
这么找到了份千里之外的工作……不过也快三年了，我觉得我的 dis-disown 特质 [fn:3] 开始发力了，有点想重新奔向一个新
的环境，可能是另一个国家？不过要达成这个目标的话我可能要将外语学习作为目标了，或许会或许不会吧。

再说到忧虑的事，即便真去了更遥远的地方，对于亲人而言本质上也没什么不同，毕竟现在一年也就只能回去两次，不过一两周。
这么说的话，和亲人真正相处的时间以人类平均年龄推断也只有四五十周的时间了。想到在我人生中占据了大半多的至亲之人在我
之后人生比例就这么缩小就有一股沮丧滋味。是的，他们很唠叨，他们不了解我……这是我当时找工作时有意识想往远点地方投，
从小学到大学的寄宿生活让我非常渴望能自己独处的状态。
但是细细想来我也不了解他们，我很惊诧我竟无法大致描绘他们的人生轨迹。或许或许，我应该拿出更多的精力投入到至亲
上面，而不是一阵无言的沉默和搪塞的嗯啊。至亲毕竟是大多数人身上最紧密的联系，我也不想让这段联系变成「宁愿在公园
躲藏 不想喝汤」 [fn:4] ……

说到联系，因为平日内存占用率太高了，好处就是我没有那么渴望社交的联系，我可以在不真实的世界找到聊以慰籍的体验来补
充对社交的渴望，但这些体验就像画中镜子反射的镜像，难以满足大脑。或许或许，我应该尝试多发起邀请，找找之前的同学
朋友联机玩游戏或聊会天什么的。或者或者，应该主动踏出自己的窝，建立新的联系。

说到关切的事，我也一直在思考，有什么办法能为我的「好奇心」这个油箱上加油呢？不过现在，已经是凌晨一点了，是
时候休息了。暗示自己，我累了，我已疲惫不堪，醒来面对新的要经历（和能感恩）的事，就这样。

** 脚注

[fn:1] 限制有时候会带来更多可能 [[/2025/12/fox-thinking-10/][FoxThinking #10: 限制会带来……]]

[fn:2] [[https://www.youtube.com/watch?v=WPPPFqsECz0][不满足的解药 - Kurzgesagt]]

[fn:3] 流浪者否认了自己的流浪，那么他就相当于以世界为家。

[fn:4] Shall We Talk - 陈奕迅
