name: Blog Deploy

on:
  push:
    branches: [ haunt-rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        sudo apt-get install wget
        python -m pip install fonttools brotli requests hy
        git config --global user.name "SouthFox"
        git config --global user.email "master@southfox.me"

    - name: Deploy
      env:
        DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY }}
        DISCUSSIONS_TOKEN: ${{ secrets.DISCUSSIONS_TOKEN }}
      run: |
        docker run -v ${{ github.workspace }}:/app southfox09/haunt-agent:latest sh -c "cd /app && GUIX_LOCPATH=/profile/lib/locale LANG=en_US.UTF-8 haunt build"
        hy utils.hy -d
        pyftsubset Zpix.ttf --text-file=strdb.txt
        fonttools ttLib.woff2 compress -o Zpix.woff2 Zpix.subset.ttf
        mv Zpix.woff2 ./site/assets/
        mv Zpix.subset.ttf ./site/assets/Zpix.ttf
        mv _headers ./site
        cd ./site
        echo "blog.southfox.me" > CNAME
        git init
        git add --all .
        git commit -m "GitHub action Auto Builder"
        git push --quiet --force https://$DEPLOY_KEY@github.com/SouthFox-D/SouthFox-D.github.io.git haunt-master
