name: Hexo Deploy

on:
  push:
    branches: [ hexo ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        sudo apt-get install wget
        python -m pip install fonttools brotli requests hy
        npm install -g hexo-cli
        npm install
        git config --global user.name "SouthFox-D"
        git config --global user.email "southfoxdreamer@gmail.com"

    - name: Deploy
      env:
        DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY }}
        DISCUSSIONS_TOKEN: ${{ secrets.DISCUSSIONS_TOKEN }}
      run: |
        hexo clean
        hexo generate
        hy utils.hy -d
        pyftsubset Zpix.ttf --text-file=strdb.txt
        fonttools ttLib.woff2 compress -o Zpix.woff2 Zpix.subset.ttf
        mv Zpix.woff2 ./public/css/fonts
        mv Zpix.subset.ttf ./public/css/fonts/Zpix.ttf
        mv _headers ./public
        cd ./public
        echo "blog.southfox.me" > CNAME
        git init
        git add --all .
        git commit -m "GitHub action Auto Builder"
        git push --quiet --force https://$DEPLOY_KEY@github.com/SouthFox-D/SouthFox-D.github.io.git master
        
